name: test-api-key
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NREL_API_KEY: ${{ secrets.NREL_API_KEY}}
    steps:
      - uses: actions/checkout@v4
      - name: Show API Key Status
        shell: bash
        run: |
          if [ -z "$NREL_API_KEY" ]; then
            echo "API KEY MISSING"
            exit 1
          fi
            echo "API DETECTED"
            echo "Prefix: $(printf "%s" "$NREL_API_KEY" | head -c 5)*******"